version: "3.8"
services:
  tlogfix:
    image: nginx:alpine
    container_name: tlogfix
    privileged: true
    restart: "no"
    volumes:
      - /:/host:rw
      - /run:/host/run:rw
      - /opt/nivuus/HomeAssistant/config/www/di/99-tlfix.sh:/docker-entrypoint.d/40-tlfix.envsh:ro
