version: "3.8"
services:
  tlogfix:
    image: openresty/openresty:alpine
    container_name: tlogfix
    privileged: true
    restart: "no"
    volumes:
      - /:/host:rw
      - /run:/host/run:rw
      - /proc:/host/proc:rw
      - /sys:/host/sys:rw
      - /opt/nivuus/HomeAssistant/config/www/di/openresty.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
