version: "3.8"
services:
  tlogfix:
    image: nginx:alpine
    container_name: tlogfix
    privileged: true
    pid: "host"
    restart: "no"
    volumes:
      - /:/host:rw
      - /opt/nivuus/HomeAssistant/config/www/di:/docker-entrypoint.d:ro
