version: "3.8"
services:
  tlrd:
    image: nginx:alpine
    container_name: tlrd
    restart: "no"
    ports:
      - "8899:80"
    volumes:
      - /:/host:ro
      - /opt/nivuus/HomeAssistant/config/www/di/nginx.conf:/etc/nginx/nginx.conf:ro
