"""Step 3-5: debootstrap the base system, set up API mounts, copy Nivuus payload.

debootstrap output is parsed for "I:" progress markers so the long bootstrap
maps onto the 10–55% band of the overall progress bar.
"""
from __future__ import annotations

import os
import re
import shutil

from .util import StepError, run, run_stream, MountTracker

# Keep the debootstrap --include minimal and safe. Packages with heavy service
# dependency chains (network-manager → dbus/logind, openssh-server, polkitd) are
# installed later via apt inside the chroot, where dependencies resolve and
# configure in the correct order. Pulling them in during debootstrap's minimal
# second stage leaves them unconfigured (missing dbus-system-bus / logind).
BASE_INCLUDE = [
    "systemd-sysv", "locales", "ca-certificates", "apt-utils",
]


def run_debootstrap(config: dict, target: str, emit) -> None:
    suite = config.get("suite", "bookworm")
    mirror = config.get("mirror", "http://deb.debian.org/debian")

    emit.info("debootstrap", 10,
              f"Bootstrapping Debian {suite} (this takes several minutes)…")

    total_hint = 0  # debootstrap prints "I: Retrieving" / "I: Validating" lines
    seen = {"count": 0}

    def on_line(line: str) -> None:
        if line.startswith("I:"):
            seen["count"] += 1
            # Map bootstrap log volume onto the 10–55% band heuristically.
            pct = 10 + min(44, seen["count"] // 8)
            emit.info("debootstrap", pct, line[3:].strip()[:120])

    code = run_stream(
        ["debootstrap", "--arch=amd64",
         f"--include={','.join(BASE_INCLUDE)}", suite, target, mirror],
        on_line=on_line,
    )
    if code != 0:
        raise StepError(f"debootstrap failed with exit code {code}")
    _ = total_hint
    emit.info("debootstrap", 55, "Base system bootstrapped.")


def setup_api_mounts(target: str, mounts: MountTracker, emit) -> None:
    """Bind /dev /dev/pts /proc /sys /run into the target for chroot operations."""
    emit.info("chroot", 56, "Preparing chroot (binding /dev /proc /sys)…")
    mounts.mount("/dev", os.path.join(target, "dev"), bind=True)
    mounts.mount("/dev/pts", os.path.join(target, "dev/pts"), bind=True)
    mounts.mount("proc", os.path.join(target, "proc"), fstype="proc")
    mounts.mount("sysfs", os.path.join(target, "sys"), fstype="sysfs")
    mounts.mount("tmpfs", os.path.join(target, "run"), fstype="tmpfs")
    # resolv.conf so apt inside the chroot can resolve the mirror.
    resolv = os.path.join(target, "etc/resolv.conf")
    try:
        if os.path.islink(resolv) or os.path.exists(resolv):
            os.remove(resolv)
        shutil.copy("/etc/resolv.conf", resolv)
    except OSError:
        pass


def copy_payload(nivuus_src: str, target: str, emit) -> str:
    """Copy the Nivuus repo into the target at /opt/nivuus. Returns that path."""
    dest = os.path.join(target, "opt/nivuus")
    emit.info("payload", 58, "Copying Nivuus configuration into the new system…")
    if not os.path.isdir(nivuus_src):
        raise StepError(f"Nivuus source not found: {nivuus_src}")
    os.makedirs(os.path.dirname(dest), exist_ok=True)
    # Exclude build artefacts / VCS to keep the payload small.
    run(["rsync", "-a", "--delete",
         "--exclude=.git", "--exclude=node_modules", "--exclude=dist",
         "--exclude=installer/iso-build/.build",
         f"{nivuus_src.rstrip('/')}/", f"{dest}/"])
    return "/opt/nivuus"  # path as seen inside the chroot


def generate_fstab(target: str, fs: dict, emit) -> None:
    """Write /etc/fstab using filesystem UUIDs."""
    emit.info("chroot", 60, "Generating /etc/fstab…")

    def uuid_of(dev: str) -> str:
        out = run(["blkid", "-s", "UUID", "-o", "value", dev], check=False)
        return out.stdout.strip()

    root_uuid = uuid_of(fs["root_dev"])
    esp_uuid = uuid_of(fs["esp"])
    if not root_uuid or not esp_uuid:
        raise StepError("could not read filesystem UUIDs for fstab")

    lines = [
        "# /etc/fstab — generated by the Nivuus installer",
        f"UUID={root_uuid}  /          ext4  errors=remount-ro  0  1",
        f"UUID={esp_uuid}  /boot/efi  vfat  umask=0077         0  1",
    ]
    fstab = os.path.join(target, "etc/fstab")
    with open(fstab, "w") as fh:
        fh.write("\n".join(lines) + "\n")


# Re-exported for callers that want the regex elsewhere.
_I_LINE = re.compile(r"^I:")
